In [1]:
import pandas as pd

In [2]:
stocks= pd.read_csv('http://bit.ly/smallstocks')

In [3]:
stocks

         Date   Close    Volume Symbol
0  2016-10-03   31.50  14070500   CSCO
1  2016-10-03  112.52  21701800   AAPL
2  2016-10-03   57.42  19189500   MSFT
3  2016-10-04  113.00  29736800   AAPL
4  2016-10-04   57.24  20085900   MSFT
5  2016-10-04   31.35  18460400   CSCO
6  2016-10-05   57.64  16726400   MSFT
7  2016-10-05   31.59  11808600   CSCO
8  2016-10-05  113.05  21453100   AAPL

In [5]:
ser= stocks.groupby(['Symbol','Date']).Close.mean()

In [6]:
ser

Symbol  Date
AAPL    2016-10-03    112.52
        2016-10-04    113.00
        2016-10-05    113.05
CSCO    2016-10-03     31.50
        2016-10-04     31.35
        2016-10-05     31.59
MSFT    2016-10-03     57.42
        2016-10-04     57.24
        2016-10-05     57.64
Name: Close, dtype: float64

In [7]:
ser.index

MultiIndex([('AAPL', '2016-10-03'),
            ('AAPL', '2016-10-04'),
            ('AAPL', '2016-10-05'),
            ('CSCO', '2016-10-03'),
            ('CSCO', '2016-10-04'),
            ('CSCO', '2016-10-05'),
            ('MSFT', '2016-10-03'),
            ('MSFT', '2016-10-04'),
            ('MSFT', '2016-10-05')],
           names=['Symbol', 'Date'])

In [9]:
df=ser.unstack()

In [12]:
df

Date    2016-10-03  2016-10-04  2016-10-05
Symbol
AAPL        112.52      113.00      113.05
CSCO         31.50       31.35       31.59
MSFT         57.42       57.24       57.64

In [13]:
ser

Symbol  Date
AAPL    2016-10-03    112.52
        2016-10-04    113.00
        2016-10-05    113.05
CSCO    2016-10-03     31.50
        2016-10-04     31.35
        2016-10-05     31.59
MSFT    2016-10-03     57.42
        2016-10-04     57.24
        2016-10-05     57.64
Name: Close, dtype: float64

In [14]:
ser.loc['AAPL']

Date
2016-10-03    112.52
2016-10-04    113.00
2016-10-05    113.05
Name: Close, dtype: float64

In [15]:
ser.loc['AAPL', '2016-10-03']

np.float64(112.52)

In [16]:
ser.loc[:, '2016-10-03']

Symbol
AAPL    112.52
CSCO     31.50
MSFT     57.42
Name: Close, dtype: float64

In [17]:
stocks

         Date   Close    Volume Symbol
0  2016-10-03   31.50  14070500   CSCO
1  2016-10-03  112.52  21701800   AAPL
2  2016-10-03   57.42  19189500   MSFT
3  2016-10-04  113.00  29736800   AAPL
4  2016-10-04   57.24  20085900   MSFT
5  2016-10-04   31.35  18460400   CSCO
6  2016-10-05   57.64  16726400   MSFT
7  2016-10-05   31.59  11808600   CSCO
8  2016-10-05  113.05  21453100   AAPL

In [18]:
stocks.set_index(['Symbol','Date'], inplace=True)
stocks

                    Close    Volume
Symbol Date
CSCO   2016-10-03   31.50  14070500
AAPL   2016-10-03  112.52  21701800
MSFT   2016-10-03   57.42  19189500
AAPL   2016-10-04  113.00  29736800
MSFT   2016-10-04   57.24  20085900
CSCO   2016-10-04   31.35  18460400
MSFT   2016-10-05   57.64  16726400
CSCO   2016-10-05   31.59  11808600
AAPL   2016-10-05  113.05  21453100

In [19]:
stocks.sort_index(inplace=True)

In [20]:
stocks

                    Close    Volume
Symbol Date
AAPL   2016-10-03  112.52  21701800
       2016-10-04  113.00  29736800
       2016-10-05  113.05  21453100
CSCO   2016-10-03   31.50  14070500
       2016-10-04   31.35  18460400
       2016-10-05   31.59  11808600
MSFT   2016-10-03   57.42  19189500
       2016-10-04   57.24  20085900
       2016-10-05   57.64  16726400

In [21]:
#using multiindex

stocks.loc['AAPL']

             Close    Volume
Date
2016-10-03  112.52  21701800
2016-10-04  113.00  29736800
2016-10-05  113.05  21453100

In [23]:
stocks.loc[('AAPL', '2016-10-03'), :]  #COLON MEANS ALL COLUMNS

Close          112.52
Volume    21701800.00
Name: (AAPL, 2016-10-03), dtype: float64

In [24]:
stocks.loc[('AAPL', '2016-10-03'), 'Close']  #ONLY CLOSE

np.float64(112.52)

In [25]:
#now we want both apple and microsoft

In [28]:
stocks.loc[(['AAPL', 'MSFT'], '2016-10-03'), :]

                    Close    Volume
Symbol Date
AAPL   2016-10-03  112.52  21701800
MSFT   2016-10-03   57.42  19189500

In [31]:
stocks.loc[('AAPL', ['2016-10-03', '2016-10-04']), :]

                    Close    Volume
Symbol Date
AAPL   2016-10-03  112.52  21701800
       2016-10-04  113.00  29736800

In [32]:
#stocks.loc[(:, ['2016-10-03', '2016-10-04']), :] does not work for all stocks you need to do:

In [33]:
stocks.loc[(slice(None), ['2016-10-03', '2016-10-04']), :]

                    Close    Volume
Symbol Date
AAPL   2016-10-03  112.52  21701800
       2016-10-04  113.00  29736800
CSCO   2016-10-03   31.50  14070500
       2016-10-04   31.35  18460400
MSFT   2016-10-03   57.42  19189500
       2016-10-04   57.24  20085900